### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by bwalsh** [smart-on-fhir/client-py#108]
Thanks for a great project.  Enjoying working with it.

Unless I've missed it, I don't see support for: 

* https://www.hl7.org/fhir/http.html#paging
* https://www.hl7.org/fhir/search.html#count

Is this correct ?

**Comment by ebrahimebrahim** [comment]
The comments here were very helpful for my project, thank you @bwalsh .

- Including the `_count` parameter in the search struct is easy and works great. Thanks for pointing this out.
- Paging can be be used manually by getting the bundle for your search via [`perform`](https://github.com/smart-on-fhir/client-py/blob/6047277daa31f10931e44ed19e92128298cdb64b/fhirclient/models/fhirsearch.py#L113) and then using the links in there to find the urls for the previous and next pages. In the case of the fhir server I was working with, the link to the next page showed up with the property `"relation": "next"`. To follow the url, you can do `smart.server.request_json(<url for next page>)`.

**Comment by anmolbhatia05** [comment]
@bwalsh @ebrahimebrahim Super helpful comments, thanks!

**Comment by bwalsh** [comment]
@anmolbhatia05 @ebrahimebrahim  glad it helped

**Comment by enkaell** [comment]
I have some reservations about the current approach. We are potentially sacrificing runtime efficiency by transitioning from working with fhirclient.models.bundle.Bundle to a standard dictionary. This requires us to convert the Bundle into a dictionary and vice versa. As you can observe from my example:

`bundle = Patient.where(struct={'_count': b'500'}).perform(smart.server)

bundle = smart.server.request_json(bundle.link[0].url)

while page := [page for page in bundle["link"] if "next" in page["relation"]]:
    page = smart.server.request_json(page[0]["url"])
    bundle = page`

I am iterating over all pages in bundle by next link. I think there's should be another solution, otherwise raw requests are simpler and faster.
