### ISSUE TITLE
valueDecimal won't accept long values

### ISSUE THREAD

**Issue by danqrodney** [smart-on-fhir/client-py#33]
Questionnaire responses can have an answer of type integer, limited to 32 bits; or they can use valueDecimal for bigger numbers.

However, if the client doesn't put a decimal point, and instead sets valueDecimal to a number that won't fit into an int (e.g. 10000000000000000000), it gets parsed as a long, and the parser gives a validation error:

<code>
FHIRValidationError: {root}: group: question: answer: valueDecimal: Wrong type &lt;type 'long'&gt; for property "valueDecimal" on $lt;class 'fhirclient.models.questionnaireresponse.QuestionnaireResponseGroupQuestionAnswer'&gt;, expecting &lt;type 'float'&gt;
</code>

Long values without decimal points should be accepted here (even if it means having to convert to a float).

**Comment by p2** [comment]
This is a current limitation since we map native Python types to many FHIR primitives, in this case [we use float for Decimal](https://github.com/smart-on-fhir/client-py/blob/master/fhirclient/models/questionnaireresponse.py#L229).

In an update we want to also use custom classes for FHIR primitives, at which point we can address this issue as well. See #30 .

**Comment by mikix** [comment]
These days, the provided example works (we use float like p2 says):

```
from fhirclient.models.questionnaireresponse import QuestionnaireResponseItemAnswer

QuestionnaireResponseItemAnswer({"valueDecimal": 10000000000000000000}).as_json()
# {'valueDecimal': 10000000000000000000}

QuestionnaireResponseItemAnswer({"valueDecimal": 10000000000000000000.00}).as_json()
# {'valueDecimal': 1e+19}
```
