### ISSUE TITLE
Improvement: pytest implementation, travis-ci for continuous integration,  flake8 for style guide enforcement

### ISSUE THREAD

**Issue by nazrulworld** [smart-on-fhir/client-py#41]
Hi @p2 
I am Nazrul, I have some suggestions to make this wonderful product to be more explicit and standard.
1. pytest: pytest is better than unittest and more powerful of course.  
2. For continuous integration we could use https://travis-ci.org/ as you know this is free for opensource project.
3. flake8 http://flake8.pycqa.org/en/latest/ undoubtedly one of the best tool that is enforcing the best coding style.
4. 100% code coverage:  we code use https://coveralls.io/ for inspection.
5. documentation improvement for developer as development guide .

I understand, you might be so busy, In that case I could manage some times, if you have agreement on those enhancements,

**Comment by mikix** [comment]
These are great ideas, of course. But might be better as separate tickets / PRs (and of course, I know I'm replying to an 8-year-old-offer-of-help).

- pytest & CI is now used (via github actions, not travis)
- flake8 or similar is a good idea - I know some members of the BCH dev team have been experimenting with [ruff](https://github.com/astral-sh/ruff) and liked it.
- code coverage - we now generate a code coverage report for every PR, but don't yet enforce it (due to [some issues](https://github.com/smart-on-fhir/client-py/commit/d4b34fc12fd6d3c127cc64e24686e165d62483d4) with forked PRs)
- documentation improvement is a lifelong goal for sure

The most actionable item remaining there is some sort of linting. I've filed #155 to track that specific ask.
