### ISSUE TITLE
FHIRDate.as_json uses original instead of isostring

### ISSUE THREAD

**Issue by yunwwang** [smart-on-fhir/client-py#69]
From fhirdate.py
```
    def as_json(self):\n
        if self.origval is not None:
            return self.origval
        return self.isostring
```
Sample code
```
date = FHIRDate('20190527T210000')
print(date.as_json())
print(date.isostring)
```
outputs
```
20190527T210000
2019-05-27T21:00:00
```
as_json() function should output the same result as isostring

**Comment by hsolbrig** [comment]
Same as https://github.com/smart-on-fhir/fhir-parser/issues/30

**Comment by mikix** [comment]
I think this is good behavior, actually.

- First off, in your example of `20190527T210000` -- that's not actually a valid FHIR datetime (needs hyphens and a timezone). (FHIRDate is loose in what it accepts today, which is a bug I'd like to fix). And I'm not being pedantic here - this actually matters for my larger point.
- With `isodate` (the parsing library that `fhirclient` uses), some information may be lost in the parsing. For example, `2017-01-01T00:00:00.123Z` -> `isodate.datetime_isoformat()` -> `2017-01-01T00:00:00Z` (we lost the milliseconds there)
- With `isodate`, we sometimes *add* information that isn't in the original spec. We parse `2024` as `2024-01-01`  for example. I don't _believe_ the spec suggests that interpretation - leaving it up to consumers (I might be wrong on that, would love correction).

So taken together - if our intermediate Python-friendly format might lose (or gain!) information and if we only accept validly formatted FHIR, I think it's both appropriate and good to return the original string during JSON round-trips to avoid corrupting the data in transit.

Now the loss and gain of info is a convenience so that library users can work with Python native date/time representations from the `datetime` stdlib - so it is often an acceptable cost depending on use case.

And for sure, we should document these edge cases better so folks know the trade-offs they're making. I'm in the middle of looking at a cleanup of how FHIRDate works that will hopefully clarify this / add more validation.

I'll optimistically close this issue for now, but if you disagree, please re-open and let's keep chatting about it.
